# Form implementation generated from reading ui file '/Users/claudiabeck/Desktop/pythonProject/venv/gui/errormsg2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_errormsg2(object):
    def setupUi(self, errormsg2):
        errormsg2.setObjectName("errormsg2")
        errormsg2.resize(347, 226)
        self.centralwidget = QtWidgets.QWidget(parent=errormsg2)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 341, 201))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.labelerror2 = QtWidgets.QLabel(parent=self.groupBox)
        self.labelerror2.setGeometry(QtCore.QRect(20, 60, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelerror2.setFont(font)
        self.labelerror2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelerror2.setWordWrap(True)
        self.labelerror2.setObjectName("labelerror2")
        errormsg2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=errormsg2)
        self.statusbar.setObjectName("statusbar")
        errormsg2.setStatusBar(self.statusbar)

        self.retranslateUi(errormsg2)
        QtCore.QMetaObject.connectSlotsByName(errormsg2)

    def retranslateUi(self, errormsg2):
        _translate = QtCore.QCoreApplication.translate
        errormsg2.setWindowTitle(_translate("errormsg2", "MainWindow"))
        self.labelerror2.setText(_translate("errormsg2", "This patient is not found in the system. Please try again."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    errormsg2 = QtWidgets.QMainWindow()
    ui = Ui_errormsg2()
    ui.setupUi(errormsg2)
    errormsg2.show()
    sys.exit(app.exec())
