# Form implementation generated from reading ui file '/Users/claudiabeck/Desktop/pythonProject/venv/gui/patientinformation.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Users import *

class Ui_Patientinfowindow(object):
    def setupUi(self, Patientinfowindow):
        Patientinfowindow.setObjectName("Patientinfowindow")
        Patientinfowindow.resize(501, 447)
        self.centralwidget = QtWidgets.QWidget(parent=Patientinfowindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 481, 411))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.title = QtWidgets.QLabel(parent=self.groupBox)
        self.title.setGeometry(QtCore.QRect(180, 20, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.name_label = QtWidgets.QLabel(parent=self.groupBox)
        self.name_label.setGeometry(QtCore.QRect(20, 70, 60, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.cpr_label = QtWidgets.QLabel(parent=self.groupBox)
        self.cpr_label.setGeometry(QtCore.QRect(20, 110, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cpr_label.setFont(font)
        self.cpr_label.setObjectName("cpr_label")
        self.address_label = QtWidgets.QLabel(parent=self.groupBox)
        self.address_label.setGeometry(QtCore.QRect(20, 160, 60, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.address_label.setFont(font)
        self.address_label.setObjectName("address_label")
        self.phone_label = QtWidgets.QLabel(parent=self.groupBox)
        self.phone_label.setGeometry(QtCore.QRect(20, 210, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.phone_label.setFont(font)
        self.phone_label.setObjectName("phone_label")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(190, 330, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.patientname = QtWidgets.QLabel(parent=self.groupBox)
        self.patientname.setGeometry(QtCore.QRect(160, 70, 301, 16))
        self.patientname.setObjectName("patientname")
        self.patientcpr = QtWidgets.QLabel(parent=self.groupBox)
        self.patientcpr.setGeometry(QtCore.QRect(160, 110, 301, 16))
        self.patientcpr.setObjectName("patientcpr")
        self.patientaddress = QtWidgets.QLabel(parent=self.groupBox)
        self.patientaddress.setGeometry(QtCore.QRect(160, 160, 301, 16))
        self.patientaddress.setObjectName("patientaddress")
        self.patientphone = QtWidgets.QLabel(parent=self.groupBox)
        self.patientphone.setGeometry(QtCore.QRect(160, 210, 301, 16))
        self.patientphone.setObjectName("patientphone")
        Patientinfowindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Patientinfowindow)
        self.statusbar.setObjectName("statusbar")
        Patientinfowindow.setStatusBar(self.statusbar)

        self.retranslateUi(Patientinfowindow)
        QtCore.QMetaObject.connectSlotsByName(Patientinfowindow)

    def retranslateUi(self, Patientinfowindow):
        _translate = QtCore.QCoreApplication.translate
        Patientinfowindow.setWindowTitle(_translate("Patientinfowindow", "MainWindow"))
        self.title.setText(_translate("Patientinfowindow", "Patient information"))
        self.name_label.setText(_translate("Patientinfowindow", "Name:"))
        self.cpr_label.setText(_translate("Patientinfowindow", "CPR-number:"))
        self.address_label.setText(_translate("Patientinfowindow", "Address:"))
        self.phone_label.setText(_translate("Patientinfowindow", "Phone number:"))
        self.pushButton.setText(_translate("Patientinfowindow", "View journal"))
        # Below we have added the set variables from the script "Users" and added the information to the labels for the sake of the example.
        self.patientname.setText(_translate("Patientinfowindow", patient_name))
        self.patientcpr.setText(_translate("Patientinfowindow", patient_CPR))
        self.patientaddress.setText(_translate("Patientinfowindow", patient_address))
        self.patientphone.setText(_translate("Patientinfowindow", patient_phone))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Patientinfowindow = QtWidgets.QMainWindow()
    ui = Ui_Patientinfowindow()
    ui.setupUi(Patientinfowindow)
    Patientinfowindow.show()
    sys.exit(app.exec())
